[package]
name = "simulator-2d"
version = "0.1.0"
authors = ["limelier"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
